Repository devpendent/website, pull requests merged in 2019-04, with the labels that each got.

#2 Development Setup
  .eslintignore
  .eslintrc
  .prettierrc
  __mocks__/file-mock.js
  __mocks__/gatsby.js
  gatsby-config.js
  gatsby-node.js
  jest-preprocess.js
  jest.config.js
  loadershim.js
  package.json
  src/components/__tests__/__snapshots__/header.js.snap
  src/components/__tests__/header.js
  src/components/header.js
  src/components/image.js
  src/components/layout.js
  src/components/seo.js
  src/pages/404.js
  src/pages/index.js
  src/pages/page-2.js
  yarn.lock
Labels: enhancement

#4 Setup Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#3 Styling Setup
  gatsby-config.js
  gatsby-node.js
  package.json
  src/components/header.js
  src/styles/_variables.sass
  yarn.lock
Labels: enhancement

#5 Format gatsby-*.js files
  gatsby-config.js
  gatsby-node.js
  package.json
Labels: enhancement

#10 Add basic setup information in README.md
  README.md
  package.json
Labels: enhancement

#9 Integration with CircleCI
  .circleci/config.yml
Labels: enhancement

#14 Integrate Codecov
  .circleci/config.yml
  .vscode/settings.json
  package.json
  src/components/__tests__/__snapshots__/header.js.snap
  src/components/__tests__/header.js
  src/components/__tests__/seo.js
Labels: enhancement

#13 Extend RenovateBot configuration
  renovate.json
Labels: chore

#17 Set Test Coverage Threshold to 100%
  README.md
  jest.config.js
  src/components/__tests__/__snapshots__/header.test.js.snap
  src/components/__tests__/__snapshots__/image.test.js.snap
  src/components/__tests__/__snapshots__/layout.test.js.snap
  src/components/__tests__/header.test.js
  src/components/__tests__/image.test.js
  src/components/__tests__/layout.test.js
  src/components/__tests__/seo.test.js
Labels: enhancement

#19 Add Pull Request template
  .github/pull_request_template.md
Labels: chore

#20 Refactor formatting scripts
  .vscode/extensions.json
  package.json
  yarn.lock
Labels: enhancement

#25 Hide Codecov token from config.yml
  .circleci/config.yml
Labels: chore

#26 Integration with antd
  gatsby-config.js
  gatsby-node.js
  package.json
  src/styles/_variables.sass
  yarn.lock
Labels: enhancement

#18 Early integration of e2e test using Cypress
  .eslintrc
  .gitignore
  README.md
  cypress.json
  cypress/e2e/home-page.js
  cypress/e2e/navigation.js
  cypress/fixtures/example.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  gatsby-node.js
  jest.config.js
  package.json
  yarn.lock
Labels: enhancement

#29 Fix :assignAndReview preset config usage in renovate.json
  renovate.json
Labels: bug

#27 Integrate Code Climate
  .github/pull_request_template.md
  README.md
Labels: enhancement

#33 Fix assignees & reviewers list
  renovate.json
Labels: bug

#35 Home Page: What & Why
  README.md
  gatsby-config.js
  package.json
  src/components/__tests__/__snapshots__/header.test.js.snap
  src/components/__tests__/__snapshots__/layout.test.js.snap
  src/components/__tests__/header.test.js
  src/components/__tests__/layout.test.js
  src/components/__tests__/seo.test.js
  src/components/header.js
  src/components/layout.js
  src/pages/index.js
Labels: enhancement

#36 Make Renovate Bot automatically merge PR if all status checks passed
  renovate.json
Labels: enhancement

#47 Fix Renovate default assignee & reviewer
  renovate.json
Labels: bug

#48 Refactor StaticQuery to hooks
  src/components/__tests__/__snapshots__/layout.test.js.snap
  src/components/__tests__/image.test.js
  src/components/__tests__/layout.test.js
  src/components/image.js
  src/components/layout.js
Labels: enhancement

#49 Remove Title from Pull Request Template
  .github/pull_request_template.md
Labels: chore
